name: Create a Teams message related to some action

inputs:
  MESSAGE:
    description: 'Message to send'
    required: true
  TEAMS_WEBHOOK:
    description: 'Teams Webhook for some Chat Channel'
    required: true

runs:
    using: "composite"
    steps:
      # Checkout the repo
    - name: Check out Repo
      uses: actions/checkout@v3
      
    # Send Chat Ops notification
    - name: Send chat ops notification to teams
      uses: dhollerbach/actions.send-message-to-ms-teams@1.0.10
      with:
        webhook: ${{ inputs.TEAMS_WEBHOOK }}
        message: ${{ inputs.MESSAGE }}
   